### ISSUE TITLE
Nedostatak validacija na formama pri dodavanju ankete

### ISSUE THREAD

**Issue by ahadzibuli1** [SoftverInzenjeringETFSA/SI2016_TIM4#16]
Kod dodavanja nove ankete nema nikakve validacije osim za prazna polja

**Comment by adnanba** [comment]
Dodana validacija za unos ankete, pitanja i naziv ankete ne smiju biti prazni. Ne smije se unijeti anketa bez pitanja. Stranica se refresha nakon unosa ankete.
